/*
Simple macro showing how to access branches from the delphes output root file,

root -l SelectDark.C'("delphes_output.root")'
*/

#ifdef __CLING__
R__LOAD_LIBRARY(libDelphes.so)
#include "classes/DelphesClasses.h"
#include "external/ExRootAnalysis/ExRootTreeReader.h"
#endif

void SelectDark(const char *inputFile) {
// Example of Root macro to copy a subset of a Tree to a new Tree
// Only selected entries are copied to the new Tree.
// The input file has been generated by the program in $ROOTSYS/test/Event
// with   Event 1000 1 99 1
//Author: Rene Brun

  gSystem->Load("libDelphes");
  gSystem->Load("libEvent.so");

  // Create chain of root trees
  TChain chain("Delphes");
  chain.Add(inputFile);
  //TChain chain2("Delphes");
  //chain2.Add("new_root.root","recreate");
  //chain2.recreate("new_root.root");
  
  // Create object of class ExRootTreeReader
  ExRootTreeReader *oldtree = new ExRootTreeReader(&chain);
  Long64_t nentries = oldtree->GetEntries();
  TClonesArray *branchMuon = oldtree->UseBranch("Muon");

  TTree* clone = chain->GetTree()->CloneTree(0);
  ExRootTreeReader *newtree = new ExRootTreeReader();

  // Create object clone
  //ExRootTreeReader *newtree = new ExRootTreeReader(&chain2);
   
  //Get old file, old tree and set top branch address
  //TFile *oldfile = new TFile("$ROOTSYS/test/Event.root");
  Event *event   = 0;
  oldtree->SetBranchAddress("event",&event);

  //Create a new file + a clone of old tree in new file
  TFile *newfile = new TFile("new_root.root","recreate");
  //TTree *newtree = oldtree->CloneTree(1);

  for (Long64_t i=0; i<nentries; i++) {
     oldtree->ReadEntry(i);
     if (branchMuon->GetEntries() > 3) newtree->Fill();
     event->Clear();
  }
  newtree->Print();
  newtree->AutoSave();
  delete oldfile;
  delete newfile;
}







